[install]
# Configuración de instalación de paquetes
production = false
dev = true
exact = false
optional = true


[run]
# Configuración de ejecución de scripts
silent = false

[test]
# Configuración de pruebas (para futuros tests)
preload = ["./test/setup.ts"]

[build]
# Configuración de build
target = "bun"
format = "esm"
