name: Update Contributors

on:
  workflow_call:

jobs:
  update-contributors:
    name: 👥 Update Contributors
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para obtener todo el historial de commits

      - name: Update Contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          # Configuración del formato
          image_size: 100
          columns_per_row: 7
          
          # Archivo a actualizar
          readme_path: 'README.md'
          
          # Configuración de commit
          commit_message: 'docs: update contributors list [skip ci]'
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Generate detailed contributors stats
        run: |
          echo "# 📊 Contributor Statistics" > CONTRIBUTORS_STATS.md
          echo "" >> CONTRIBUTORS_STATS.md
          echo "## Top Contributors by Commits" >> CONTRIBUTORS_STATS.md
          echo "" >> CONTRIBUTORS_STATS.md
          
          # Obtener top contributors por commits
          git log --format='%aN' | sort | uniq -c | sort -rn | head -10 | while read count name; do
            echo "- **$name**: $count commits" >> CONTRIBUTORS_STATS.md
          done
          
          echo "" >> CONTRIBUTORS_STATS.md
          echo "## Recent Activity" >> CONTRIBUTORS_STATS.md
          echo "" >> CONTRIBUTORS_STATS.md
          
          # Últimos 10 commits con autores
          git log --oneline --format='%h %s (%an, %ar)' -10 | while read commit; do
            echo "- $commit" >> CONTRIBUTORS_STATS.md
          done
          
          echo "" >> CONTRIBUTORS_STATS.md
          echo "---" >> CONTRIBUTORS_STATS.md
          echo "*Updated automatically by GitHub Actions*" >> CONTRIBUTORS_STATS.md

      - name: Update contributor statistics
        run: |
          # Mover estadísticas al directorio docs
          mv CONTRIBUTORS_STATS.md docs/
          
          # Commit si hay cambios
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to contributor statistics"
          else
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add docs/CONTRIBUTORS_STATS.md
            git commit -m "docs: update contributor statistics [skip ci]" || true
            git push origin develop || true
          fi
